<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://change-this-to-the-site-you-are-testing/" />
<title>try_catch_function_definitions_case</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">try_catch_case</td></tr>
</thead><tbody>
<tr>
	<td>function</td>
	<td>try_catch_by_error_type</td>
	<td></td>
</tr>
<tr>
	<td>getEval</td>
	<td>storedVars.exceptionCaught= undefined</td>
	<td></td>
</tr>
<tr>
	<td>try</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>getEval</td>
	<td>throw &quot;An exception&quot;</td>
	<td></td>
</tr>
<tr>
	<td>catch</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>storeEval</td>
	<td>true</td>
	<td>exceptionCaught</td>
</tr>
<tr>
	<td>endTry</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>getEval</td>
	<td>if( !storedVars.exceptionCaught ) throw &quot;try_catch_function_definitions_case: The first try...catch should have caught an exception&quot;</td>
	<td></td>
</tr>
<!---->
<tr>
	<td>getEval</td>
	<td>storedVars.assertCaught= undefined</td>
	<td></td>
</tr>
<tr>
	<td>try</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>assertEval</td>
	<td>false</td>
	<td></td>
</tr>
<tr>
	<td>catch</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>storeEval</td>
	<td>true</td>
	<td>assertCaught</td>
</tr>
<tr>
	<td>endTry</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>getEval</td>
	<td>if( !storedVars.assertCaught ) throw &quot;try_catch_function_definitions_case: The second try...catch should have caught an assert failure&quot;</td>
	<td></td>
</tr>
<!---->
<tr>
	<td>getEval</td>
	<td>storedVars.verifyCaught= undefined</td>
	<td></td>
</tr>
<tr>
	<td>try</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>verifyEval</td>
	<td>false</td>
	<td></td>
</tr>
<tr>
	<td>storeEval</td>
	<td>true</td>
	<td>verifyNotCaught</td>
</tr>
<tr>
	<td>catch</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>getEval</td>
	<td>throw &quot;try_catch_function_definitions_case: verification failure in the third try...catch&quot;</td>
	<td></td>
</tr>
<tr>
	<td>endTry</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>getEval</td>
	<td>if( !storedVars.verifyNotCaught ) throw &quot;try_catch_function_definitions_case: The third try...catch should have not caught a verification failure&quot;</td>
	<td></td>
</tr>
<!---->
<tr>
	<td>getEval</td>
	<td>storedVars.nonExistingElementOperationCaught= undefined</td>
	<td></td>
</tr>
<tr>
	<td>try</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>nonExistingElementLocator</td>
	<td></td>
</tr>
<tr>
	<td>catch</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>storeEval</td>
	<td>true</td>
	<td>nonExistingElementOperationCaught</td>
</tr>
<tr>
	<td>endTry</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>getEval</td>
	<td>if( !storedVars.nonExistingElementOperationCaught) throw &quot;try_catch_function_definitions_case: Operation on a non-existing element should trigger catch handler in fourth try...catch&quot;</td>
	<td></td>
</tr>
<tr>
	<td>endFunction</td>
	<td>try_catch_by_error_type</td>
	<td></td>
</tr>
<!---->
<tr>
	<td>call</td>
	<td>try_catch_by_error_type</td>
	<td></td>
</tr>
<!---->
<!--Simple function that throws an error. To be called from within try..catch.-->
<tr>
	<td>function</td>
	<td>throwAnError</td>
	<td></td>
</tr>
<tr>
	<td>throw</td>
	<td>'An error'</td>
	<td></td>
</tr>
<tr>
	<td>endFunction</td>
	<td>throwAnError</td>
	<td></td>
</tr>
<!---->
<tr>
	<td>getEval</td>
	<td>storedVars.errorThrownFromFunction= undefined</td>
	<td></td>
</tr>
<tr>
	<td>try</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>call</td>
	<td>throwAnError</td>
	<td></td>
</tr>
<tr>
	<td>catch</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>storeEval</td>
	<td>true</td>
	<td>errorThrownFromFunction</td>
</tr>
<tr>
	<td>endTry</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>getEval</td>
	<td>if( !storedVars.errorThrownFromFunction) throw new Error( &quot;try_catch_function_definitions_case: Call to function throwAnError in the fifth try..catch should have thrown an error that should have been caught.&quot; );</td>
	<td></td>
</tr>
<!---->
<tr>
	<td>promise</td>
	<td>new Promise( resolve=&gt;setTimeout( ()=&gt;{resolve(1);}, 200 ) )</td>
	<td>promise</td>
</tr>
<tr>
	<td>storePromise</td>
	<td>new Promise( ()=&gt;{} )</td>
	<td>never</td>
</tr>
<tr>
	<td>storePromise</td>
	<td>new Promise( (resolve, reject)=&gt;{ window.setTimeout( reject, 200); } )</td>
	<td>never</td>
</tr>
<tr>
	<td>storePromise</td>
	<td>new Promise( (resolve, reject)=&gt;{ window.setTimeout( ()=&gt;resolve(1), 200); } )</td>
	<td>one</td>
</tr>
<tr>
	<td>storePromise</td>
	<td>new Promise( (resolve)=&gt;{ resolve(true); } )</td>
	<td>true</td>
</tr>
<tr>
	<td>storePromise</td>
	<td>new Promise( (resolve)=&gt;{ resolve(false); } )</td>
	<td>false</td>
</tr>
<tr>
	<td>getEval</td>
	<td>alert( storedVars.false===false )</td>
	<td></td>
</tr>
<tr>
	<td>storePromise</td>
	<td>new Promise( (resolve)=&gt;{ resolve(undefined); } )</td>
	<td>undefined</td>
</tr>
<tr>
	<td>storePromise</td>
	<td>new Promise( (resolve)=&gt;{ resolve(null); } )</td>
	<td>null</td>
</tr>
<!---->
<tr>
	<td>ifPromise</td>
	<td>new Promise( (resolve, reject)=&gt;{ window.setTimeout( ()=&gt;resolve(1), 500); } )</td>
	<td></td>
</tr>
<tr>
	<td>log</td>
	<td>promise equaled true</td>
	<td></td>
</tr>
<tr>
	<td>endIfPromise</td>
	<td></td>
	<td></td>
</tr>
<!---->
<tr>
	<td>if</td>
	<td>false</td>
	<td></td>
</tr>
<!--        getEval() that times out. It caused Selenium IDE 2.9.1 and Firefox 46.0.1 run away/freeze!-->
<tr>
	<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;getEval</td>
	<td>var nowMilliSec=Date.now(); while( Date.now()-nowMilliSec&lt;selenium.defaultTimeout+100 ); LOG.info('getEval finished while() loop, even though it was overtime.');</td>
	<td></td>
</tr>
<tr>
	<td>promise</td>
	<td>new Promise( ()=&gt;'never' )</td>
	<td></td>
</tr>
<tr>
	<td>endIf</td>
	<td></td>
	<td></td>
</tr>
<!---->
<!--Promises that times out:-->
<tr>
	<td>getEval</td>
	<td>$promiseTimedOut= undefined</td>
	<td></td>
</tr>
<tr>
	<td>try</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>&nbsp;&nbsp;&nbsp;&nbsp;promise</td>
	<td>new Promise( resolve =&gt; window.setTimeout( ()=&gt;resolve(1), selenium.defaultTimeout+100) )</td>
	<td></td>
</tr>
<tr>
	<td>catch</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>&nbsp;&nbsp;&nbsp;&nbsp;storeEval</td>
	<td>true</td>
	<td>promiseTimedOut</td>
</tr>
<tr>
	<td>endTry</td>
	<td></td>
	<td></td>
</tr>
<!---->
<tr>
	<td>getEval</td>
	<td>if( !$promiseTimedOut) { throw new Error( &quot;XXX _case: A promise should have timed out.&quot; ); }</td>
	<td></td>
</tr>
<tr>
	<td>getEval</td>
	<td>alert( $promiseTimedOut===undefined)</td>
	<td></td>
</tr>
<!---->
<tr>
	<td>&nbsp;&nbsp;&nbsp;&nbsp;waitForElementPresent</td>
	<td>id=cuckoo</td>
	<td></td>
</tr>
<!---->
<tr>
	<td>&nbsp;&nbsp;&nbsp;&nbsp;getEval</td>
	<td>debugger; throw new Error('thrown')</td>
	<td></td>
</tr>
<!---->
<tr>
	<td>try</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>&nbsp;&nbsp;&nbsp;&nbsp;promise</td>
	<td>new Promise( ()=&gt;'never' )</td>
	<td></td>
</tr>
<tr>
	<td>catch</td>
	<td></td>
	<td></td>
</tr>
<tr>
	<td>&nbsp;&nbsp;&nbsp;&nbsp;getEval</td>
	<td>alert('caught')</td>
	<td></td>
</tr>
<tr>
	<td>endTry</td>
	<td></td>
	<td></td>
</tr>
<!---->
<tr>
	<td>storeEval</td>
	<td>[&quot;hi&quot;, &quot;mate&quot;][Symbol.iterator]()</td>
	<td>itr</td>
</tr>
<!---->
<tr>
	<td>forIterator</td>
	<td>value</td>
	<td>[&quot;hi&quot;, &quot;mate&quot;][Symbol.iterator]()</td>
</tr>
<tr>
	<td>&nbsp;&nbsp;&nbsp;&nbsp;log</td>
	<td>${value}</td>
	<td>warn</td>
</tr>
<tr>
	<td>endForIterator</td>
	<td></td>
	<td></td>
</tr>
</tbody></table>
</body>
</html>
